### PR TITLE
Update arithmetic fail.py

### PR DESCRIPTION
**Pull request by A1fus**
- added a name input field
- fixed a spelling error
- changed the values for selecting numbers
- added a multiply question
- made it add one to the score when the question is answered correctly
- added an unlucky message if the question was answered incorrectly
- added a comment explaining that last thing that needs to be done

### CODE REVIEW

**Comment by A1fus** [comment]
:boom:

**Comment by A1fus** [comment]
:camel:

**Comment by A1fus** [comment]
:sparkles:

**Comment by A1fus** [comment]
:basketball:

**Comment by A1fus** [comment]
:dance:

**Comment by A1fus** [comment]
:four_leaf_clover:

**Comment by AlexEaton1105** [comment]
:100:

**Comment by A1fus** [comment]
:jack_o_lantern:

**Pull request merged**
